import numpy as np

# Random seed
SEED = 42
np.random.seed(SEED)

# config.py

ANALYSIS_FILE = "data/sample_data.csv"   # path to CSV generated by pipeline
VERSION = "1.0"                           # report version
PLOTS_DIR = "plots"                       # folder where all plots are saved

# RL Parameters
RL_PARAMS = {
    "epsilon": 0.1,
    "decay": 0.99,
    "gamma": 0.9,
    "episodes": 100
}

# Paths
DATA_FILE = "data/sample_data.csv"
RESULTS_FILE = "aggregated_results.csv"

# Model parameters
RF_PARAMS = {
    "n_estimators": 200,
    "max_depth": 8,
    "random_state": SEED
}

# Deployment group simulation
DEPLOYMENT_GROUP = {
    "G1": {"alpha": 0.1},
    "G4": {"alpha": 0.5}
}
